NDefines.NMilitary.PLAN_SPREAD_ATTACK_WEIGHT = 4
NDefines.NMilitary.PLAYER_ORDER_PLANNING_DECAY = 0.01
NDefines.NAI.RESERVE_TO_COMMITTED_BALANCE = 0.3
NDefines.NAI.ORG_UNIT_WEAK = 0.40
NDefines.NAI.ORG_UNIT_NORMAL = 0.75
NDefines.NAI.STR_UNIT_WEAK = 0.40
NDefines.NAI.STR_UNIT_NORMAL = 0.75